version: '3.3'
services:
  db:
    image: mysql:5.7.25
    restart: always
    volumes:
        - mysql_hibernate:/var/lib/mysql_hibernate
    container_name: hibernate-mysql-standalone
    environment:
      MYSQL_DATABASE: 'hibernate'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
# Names our volume
volumes:
  mysql_hibernate:
